services:
  backend:
    image: banchani/hambook.v3-fastapi:3.0
    container_name: hambook.v3-fastapi
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_HOST=hambook-db
      - REDIS_HOST=hambook-redis
    depends_on:
      hambook-db:
        condition: service_healthy
      hambook-redis:
        condition: service_started
    networks:
      - app-network

  frontend:
    image: banchani/hambook.v3-react:3.0
    container_name: hambook.v3-react
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt # 인증서가 저장될 곳
      - ./certbot/www:/var/www/certbot   # 인증용 임시 파일이 놓일 곳
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # 12시간마다 한 번씩 인증서 갱신이 필요한지 체크
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  hambook-db:
    image: banchani/hambook.v3-mysql:3.0
    container_name: hambook-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4010gg4010gg
      MYSQL_DATABASE: hambook
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p4010gg4010gg"]
      timeout: 20s
      retries: 10

  hambook-redis:
    image: banchani/hambook.v3-redis:3.0
    container_name: hambook-redis
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: